### PR TITLE
fix(formatCurrency.js): Added toFixed to the currency formatting.

### LINKED ISSUE #11: Amounts have no trailing zeros
Example: Balance is £100.50 and the bar will show "£100.5"

### PR DESCRIPTION
**Pull request by ryanb93**
fix #11

### CODE REVIEW

**Comment by johneas10** [comment]
Thanks this is great!

Can you squash the first commit?

**Comment by ryanb93** [comment]
@johneas10 squished :)

**Comment by ryanb93** [comment]
@johneas10 replaced it with "Replaced toFixed call with toLocaleString's minimumFractionDigits parameter"

**Comment by johneas10** [comment]
cheers mate!

**Pull request merged**
