### PR TITLE
Added transactions for today

### PR DESCRIPTION
**Pull request by ryanb93**
Basic implementation to show transactions made today

### CODE REVIEW

**Comment by ryanb93** [comment]
Missing tests for new URL path

**Comment by johneas10** [comment]
Hi Ryan,

I've pulled this down and had a quick look.

A few issues I had with it:
- the transactions aren't in order
- pots transactions are included, should we remove them?
- the transaction details can be a bit messy

I think we can still do a bit of work to get this right. I've been playing around with some ideas myself.
Are you on the Monzo slack channel?

**Comment by ryanb93** [comment]
@johneas10 added a filter for removing pots, added `&expand[]=merchant` which gave access to a nicely formatted Merchant name. Don't have enough transactions for me to test on today but could always sort by the `t.settled` date?

**Comment by johneas10** [comment]
Hey! Branch looks good now. Can you run commitizen on it and I'll get it merged! 👍🏻

**Comment by johneas10** [comment]
Yeah that would be great. Apparently nobody ever sends me money 👎

**Comment by ryanb93** [comment]
@johneas10 Added the filter and committed using commitizen, ready for merge

**Pull request merged**
